%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\matlab\DataAna\2011-2015住院-并发症-记录-3万6.xlsx
%    Worksheet: Sheet2
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/04/02 21:06:13

%% Import the data
[~, ~, raw0_0] = xlsread('E:\matlab\DataAna\2011-2015住院-并发症-记录-3万6.xlsx','Sheet2','A2:A36337');
[~, ~, raw0_1] = xlsread('E:\matlab\DataAna\2011-2015住院-并发症-记录-3万6.xlsx','Sheet2','C2:C36337');
[~, ~, raw0_2] = xlsread('E:\matlab\DataAna\2011-2015住院-并发症-记录-3万6.xlsx','Sheet2','E2:E36337');
[~, ~, raw0_3] = xlsread('E:\matlab\DataAna\2011-2015住院-并发症-记录-3万6.xlsx','Sheet2','H2:I36337');
raw = [raw0_0,raw0_1,raw0_2,raw0_3];
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,5);
raw = raw(:,[1,2,3,4]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
ID = data(:,1);
age = data(:,2);
sex = data(:,3);
c_sno = data(:,4);
c_name = cellVectors(:,1);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1 raw0_2 raw0_3 cellVectors R;